### ISSUE TITLE
经常不生效 2022版idea或2023都有

### ISSUE THREAD

**Issue by 13612687938** [starxg/mybatis-log-plugin-free#15]
老出现这个情况
![image](https://user-images.githubusercontent.com/51987247/233826499-e97df5fa-6b7d-4f28-9ed5-3c70445c684c.png)

**Comment by hczs** [comment]
> 老出现这个情况 ![image](https://user-images.githubusercontent.com/51987247/233826499-e97df5fa-6b7d-4f28-9ed5-3c70445c684c.png)

开启 mybatis DEBUG 日志即可，IDEA 2023.1 测试可用
