### ISSUE TITLE
所有的sql语句全是红色的，不好分辨是那种sql

### ISSUE THREAD

**Issue by RaKaiYli** [starxg/mybatis-log-plugin-free#6]
使用起来还是相当不错的，但是所有的sql语句全是红色的，不好分辨是查的sql还是插入的sql

**Comment by starxg** [comment]
或许可以加一个自定义 SQL 颜色的，INSERT 什么颜色 ，DELETE 什么颜色 ......

**Comment by starxg** [comment]
1.3.0 支持自定义颜色
