### ISSUE TITLE
2021.3.1 使用1.3.0的版本没有左侧修改颜色，下拉箭头等功能

### ISSUE THREAD

**Issue by Kang-kin** [starxg/mybatis-log-plugin-free#9]
![微信截图_20220424121820](https://user-images.githubusercontent.com/68142725/164956475-a4ecf085-9f84-4fd7-8bfb-ad2381ccdd36.png)

**Comment by starxg** [comment]
![image](https://user-images.githubusercontent.com/34997494/173169145-960406be-2a5a-4bd1-9bf7-e058ed40d98a.png)
试了一下，我看是可以的啊
